name: flutter_getx_template
description: Boilarplate template of Flutter GetX.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: "2.8.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.4
  get: ^4.5.1
  flutter_svg: ^2.0.7
  dio: ^5.2.1+1
  shared_preferences: ^2.0.10
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0
  animations: ^2.0.2
  logger: ^1.1.0
  pretty_dio_logger: ^1.1.1
  font_awesome_flutter: ^10.4.0
  fluttertoast: ^8.0.8
  rive: ^0.11.3
  carousel_slider: ^4.2.1
  flutter_rating_bar: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  analyzer: any
  dart_code_metrics: any
  change_app_package_name: ^1.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "images/launcher_icon.png"
  

flutter:
  generate: true
  uses-material-design: true
  assets:
    - images/
    - assets/product_list.json
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Thin.ttf
          weight: 200
        - asset: fonts/Roboto-Light.ttf
          weight: 200
        - asset: fonts/Roboto-Regular.ttf
          weight: 200
        - asset: fonts/Roboto-Medium.ttf
          weight: 300
        - asset: fonts/Roboto-Bold.ttf
          weight: 600
        - asset: fonts/Roboto-Italic.ttf
          style: italic
